export const COUNTRY_NAMES: Record<string, string> = {
  'ALB': 'Albania',
  'AND': 'Andorra',
  'AUT': 'Austria',
  'BEL': 'Belgium',
  'BGR': 'Bulgaria',
  'BIH': 'Bosnia and Herzegovina',
  'CHE': 'Switzerland',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'DEU': 'Germany',
  'DNK': 'Denmark',
  'ESP': 'Spain',
  'EST': 'Estonia',
  'FIN': 'Finland',
  'FRA': 'France',
  'GRC': 'Greece',
  'HRV': 'Croatia',
  'HUN': 'Hungary',
  'IRL': 'Ireland',
  'ISL': 'Iceland',
  'ITA': 'Italy',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'LVA': 'Latvia',
  'MCO': 'Monaco',
  'MDA': 'Moldova',
  'MKD': 'North Macedonia',
  'MLT': 'Malta',
  'MNE': 'Montenegro',
  'NLD': 'Netherlands',
  'NOR': 'Norway',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'ROU': 'Romania',
  'SMR': 'San Marino',
  'SRB': 'Serbia',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SWE': 'Sweden',
  'UKR': 'Ukraine',
  'VAT': 'Vatican City',
  'GBR': 'United Kingdom',
  'BLR': 'Belarus'
};
